DEPTH=../../../..

include $(CURDIR)/$(DEPTH)/make/mmd.mak

TARGETS := \
  _test_keyval1_lexer.mmd \
  _test_keyval1_lexer.svg \
  _test_keyval1_lexer.py \
  _test_keyval2_lexer.mmd \
  _test_keyval2_lexer.svg \
  _test_keyval2_lexer.py \
  $(NULL)

all: $(TARGETS)

clean:
	rm -f $(TARGETS)
