stateDiagram-v2
  direction LR
  [*] --> start
  start --> [*]: eos
  start --> comment: [#0059;]
  start --> space: [\t ␠]
  start --> cr: [␍]
  start --> section_name: [
  start --> key: [_ a-z A-Z 0-9]
  space --> space: [\t ␠]
  space --> [*]: eos
  space --> cr: [␍]
  space --> start: [␤]
  space --> key: [_ a-z A-Z 0-9]
  cr --> start: [␤] 
  cr --> cr_error: [.] eos
  note right of cr_error
    Expecting "␤" instead of "."
  end note
  comment --> comment: [.]
  comment --> cr: [␍]
  comment --> start: [␤]
  comment --> [*]: eos
  section_name --> section_name: [_ a-z A-Z 0-9 \.]
  section_name --> start: ]
  section_name --> section_name_error: [\t ␠ ␍ ␤] eos
  note left of section_name_error
    Unexpected char in section name
  end note
  key --> key: [_ a-z A-Z 0-9 \.]
  key --> key_space: [\t ␠]
  key --> value_space: [=]
  key_space --> key_space: [\t ␠]
  key_space --> error5: [␍␤] eos
  key_space --> value_space: [=]
  value_space --> value_space: [\t ␠]
  value_space --> error6: [␍␤] eos
  value_space --> value: [.]
  value --> value: [.]
  value --> space: [\t ␠]
  value --> cr: [␍]
  value --> start: [␤]
  value --> [*]: eos
