stateDiagram-v2
  direction LR
  [*] --> Start
  Start --> [*]
  Start --> Comment: [#0059;]
  Start --> Space: [\t␠]
  Start --> Space: [\t␠]
  Space --> Space: [\t␠]
  Space --> Crash
  Comment --> Comment: [.]
  Comment --> [*]: EOS
  Crash --> [*]
