#-*- coding:utf-8; mode:python; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*-

class text_lexer_char:
  AMPERSAND = '&'
  AT = '@'
  BACK_SLASH = '\\'
  BANG = '!'
  CARET = '^'
  CLOSE_BRACKET = ']'
  CLOSE_CURLY_BRACKET = '}'
  CLOSE_PARENTHESIS = ')'
  COLON = ':'
  COMMA = ','
  CR = '\r'
  DIGIT = '0123456789'
  DOLLAR = '$'
  DOUBLE_QUOTE = "\""
  EOS = '\0'
  EQUAL = '='
  GRAVE_ACCENT = '`'
  GREATER_THAN = '>'
  HASH = '#'
  LESS_THAN = '<'
  LOWER_LETTER = 'abcdefghijklmnopqrstuvwxyz'
  MINUS = '-'
  NL = '\n'
  OPEN_BRACKET = '['
  OPEN_CURLY_BRACKET = '{'
  OPEN_PARENTHESIS = '('
  PERCENT = '%'
  PERIOD = '.'
  PIPE = '|'
  PLUS = '+'
  QUESTION_MARK = '?'
  SEMICOLON = ';'
  SINGLE_QUOTE = '\''
  SLASH = '/'
  SPACE = ' '
  STAR = '*'
  TAB = '\t'
  TILDE = '~'
  UNDERSCORE = '_'
  UPPER_LETTER = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
