DEPTH=../../../..

include $(CURDIR)/$(DEPTH)/make/mmd.mak

TARGETS := \
  bc_ini_lexer.mmd \
  bc_ini_lexer.svg \
  bc_ini_lexer.py \
  bc_ini_parser.mmd \
  bc_ini_parser.svg \
  bc_ini_parser.py \
  $(NULL)

all: $(TARGETS)

clean:
	rm -f $(TARGETS)

touch:
	@touch *.bt*
